[package]
name = "test-matterfi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-types = "1.5.0"
bs58 = "0.4.0"
hex = "*"
blake2 = { version = "0.9.0", default-features = false }
